---@type NvPluginSpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "vim",
      "lua",
      "vimdoc",
      "html",
      "css",
      "c",
      "bash",
      "cmake",
      "cpp",
      "csv",
      "dockerfile",
      "git_config",
      "git_rebase",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "gowork",
      "java",
      "javascript",
      "json5",
      "make",
      "rust",
      "sql",
      "typescript",
      "xml",
      "yaml",
      "python",
      "hcl",
      "terraform",
      "proto",
      "erlang",
      "elixir",
    },
  },
}
